

service: drinkstore-forecasting-getData


provider:
  name: aws
  runtime: python3.8
  region: ap-southeast-1

custom:
  pythonRequirements:
    dockerizePip: true

package:
  individually: false
  exclude:
    - package.json
    - package-log.json
    - node_modules/**

functions:
  get_avg_temp:
    handler: getData.get_avg_temp_tpi
    events:
      - http:
          path: forecast/get_avg_temp
          method: get
          async: True

  get_order_amount:
    handler: getData.get_order_amount
    events:
      - http:
          path: forecast/get_order_amount
          method: get
          async: True

  get_future_temp:
    handler: getData.get_future_temp
    events:
      - http:
          path: forecast/get_future_temp
          method: get
          async: True

  machine_learning:
    handler: getData.machine_learning
    events:
      - http:
          path: forecast/machine_learning
          method: get
          async: True

  clean_dashboard_data:
    handler: getData.clean_dashboard_data
    events:
      - http:
          path: forecast/clean_dashboard_data
          method: get
          async: True





plugins:
  - serverless-python-requirements
